# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: quding0308's blog
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.quding0308.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: quding0308
# github_username:  quding0308

# Build settings
markdown: kramdown
theme: minima

# 参考：
# https://github.com/merenlab/web/blob/master/_config.yml
# https://github.com/tudelft3d/geo5010/blob/master/_config.yml


kramdown:
  # auto_ids: true
  footnote_nr: 1
  # entity_output: as_char
  toc_levels: 1..4
  # enable_coderay: false

# plugins:
  # - jekyll-feed

paginate: 5
# paginate_path: "page:num"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
